M48
; DRILL file {KiCad 6.0.2-378541a8eb~116~ubuntu20.04.1} date Fri 27 Jan 2023 04:36:06 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-27T16:36:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2-378541a8eb~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.785
%
G90
G05
T1
X46.8Y-94.9
T0
M30
